#!/bin/bash

# --- To use reprozip, python is required. Install the python or uncomment the below lines ---
# Install Python
# apt-get install -y python python-dev python-pip gcc libsqlite3-dev libssl-dev libffi-dev
# Install Reprozip
# pip install -U reprozip

# Get run arguments. For e.g., python demo.py
run_args="$@"

# change directory to current directory
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

# Run your program with reprozip
reprozip trace $run_args

# Get the project folder from run arguments
IFS='//' read -r -a array <<< "$run_args"
project_name=${array[1]}
project_dir=run/${project_name}

# Move reprozip output to project directory. For e.g., run/python-demo/config
mv .reprozip-trace ${project_dir}/linchpin-config

# Invoke yml to JSON parser - It will generate config.json
python parsers/yml_to_json.py ${project_dir}/linchpin-config/config.yml

# Invoke JSON to Dockerfile generator
python parsers/json_to_docker.py ${project_dir}/linchpin-config/config.json

# Generate tar file containing Dockerfile and project files
cd "$project_dir"
mkdir "linchpin-tar"
cp linchpin-config/Dockerfile linchpin-tar/Dockerfile
mkdir linchpin-tar/${project_name}
rsync -a --exclude linchpin-config --exclude linchpin-tar * linchpin-tar/${project_name} 
cd "linchpin-tar"
tar -zcvf ${project_name}.tar *

# Move tar file to linchpin-config
mv ${project_name}.tar ../linchpin-config/
cd ../
rm -r linchpin-tar
